import os

print("""
███████╗██╗██████╗░██████╗░██╗
╚════██║██║██╔══██╗██╔══██╗██║
░░███╔═╝██║██║░░██║██║░░██║██║
██╔══╝░░██║██║░░██║██║░░██║██║
███████╗██║██████╔╝██████╔╝██║
╚══════╝╚═╝╚═════╝░╚═════╝░╚═╝

TG CHANNEL ~ @nobi_shops | YT ~ ziddi_shop |
Starting, please do not close the code until the 'Program Finished' message appears.
""")


os.system('pip install OneClick')
os.system('pip install stdiomask')
os.system('pip install user_agent')
os.system('pip install instaloader')
os.system('pip install requests')
os.system('pip install rich')
os.system('user_agent')
os.system('instaloader')
os.system('mechaize')
os.system('pip install pyfiglet')
os.system('pip install sys')
os.system('pip install py_compile')
os.system('pip install youtube_dl')
os.system('pip install uuid')
os.system('pip install time')
os.system('pip install os')
os.system('pip install random')
os.system('pip install datetime')
os.system('pip install string')
os.system('pip install secrets')
os.system('pip install webbrowser')
os.system('pip install hashlib')
os.system('pip install colorama')
os.system('pip install n')
os.system('pip install mm')
os.system('pip install new')
os.system('pip install sleep')
os.system('pip install BeautifulSoup')
os.system('pip install new')
os.system('pip install pafy')
os.system('pip install bs4')
os.system('pip install sys')
os.system('pip install json')
os.system('pip install random')
os.system('pip install uuid')
os.system('pip install secrets')
os.system('pip install datetime')
os.system('pip install *')
os.system('pip install argparse')
os.system('pip install InstagramAPI')
os.system('pip install sleep')
os.system('pip install string')
os.system('pip install uuid4')
os.system('pip install generate_user_agent')
os.system('pip install threading')
os.system('pip install json')
os.system('pip install datetime')
os.system('pip install token_hex')
os.system('pip install secrets')
os.system('pip install token_hex')
os.system('pip install Fore')
os.system('pip install secrets')
os.system('pip install uuid')
os.system('pip install re')
os.system('pip install b')
os.system('pip install requests')
os.system('pip install pyfiglet')
os.system('pip install selenium')
os.system('pip install requests')
os.system('pip install pyfiglet')
os.system('pip install sys')
os.system('pip install py_compile')
os.system('pip install youtube_dl')
os.system('pip install uuid')
os.system('pip install time')
os.system('pip install os')
os.system('pip install random')
os.system('pip install datetime')
os.system('pip install string')
os.system('pip install secrets')
os.system('pip install webbrowser')
os.system('pip install hashlib')
os.system('pip install colorama')
os.system('pip install n')
os.system('pip install mm')
os.system('pip install new')
os.system('pip install sleep')
os.system('pip install BeautifulSoup')
os.system('pip install new')
os.system('pip install pafy')
os.system('pip install bs4')
os.system('pip install sys')
os.system('pip install json')
os.system('pip install random')
os.system('pip install uuid')
os.system('pip install secrets')
os.system('pip install datetime')
os.system('pip install argparse')
os.system('pip install InstagramAPI')
os.system('pip install sleep')
os.system('pip install string')
os.system('pip install uuid4')
os.system('pip install generate_user_agent')
os.system('pip install threading')
os.system('pip install json')
os.system('pip install datetime')
os.system('pip install token_hex')
os.system('pip install secrets')
os.system('pip install token_hex')
os.system('pip install Fore')
os.system('pip install secrets')
os.system('pip install uuid')
os.system('pip install re')
os.system('pip install b')
os.system('pip install requests')
os.system('pip install pyfiglet')
os.system('pip install sys')
os.system('pip install py_compile')
os.system('pip install youtube_dl')
os.system('pip install uuid')
os.system('pip install time')
os.system('pip install os')
os.system('pip install random')
os.system('pip install datetime')
os.system('pip install string')
os.system('pip install secrets')
os.system('pip install webbrowser')
os.system('pip install hashlib')
os.system('pip install colorama')
os.system('pip install n')
os.system('pip install mm')
os.system('pip install new')
os.system('pip install sleep')
os.system('pip install BeautifulSoup')
os.system('pip install new')
os.system('pip install pafy')
os.system('pip install bs4')
os.system('pip install sys')
os.system('pip install json')
os.system('pip install random')
os.system('pip install uuid')
os.system('pip install secrets')
os.system('pip install datetime')
os.system('pip install *')
os.system('pip install argparse')
os.system('pip install InstagramAPI')
os.system('pip install sleep')
os.system('pip install string')
os.system('pip install uuid4')
os.system('pip install generate_user_agent')
os.system('pip install threading')
os.system('pip install json')
os.system('pip install datetime')
os.system('pip install token_hex')
os.system('pip install secrets')
os.system('pip install token_hex')
os.system('pip install Fore')
os.system('pip install secrets')
os.system('pip install uuid')
os.system('pip install re')
os.system('pip install b')
os.system('cls' if os.name == 'nt' else 'clear') 
print('Bitti')
